services:
  - type: web
    name: peptide-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker app:app --workers 2 --threads 8 --timeout 120 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: MODEL_DIR
        value: "model_saved"
    autoDeploy: true
